name: alert-notification

on: 
  workflow_dispatch:
    inputs:
      payload:
        description: 'JSON Payload'
        required: true

jobs: 
  run-script:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if operation is Create
        id: check-operation
        run: |
          operation=$(echo "${{ toJson(github.event.inputs.payload) }}" | tr -d '\r' | jq -r '.operation')
          if [[ "$operation" == "Create" ]]; then
            echo "Operation is Create"
          else 
            echo "Operation is not Create. Skip"
            exit 0
          fi

      - name: Extract data
        if: steps.check-operation.outputs['check-operation'] == 'Operation is Create'
        id: extract-data
        run: | 
          # Extract data and store in environment variable
          data=$(echo "${{ toJson(github.event.inputs.payload) }}" | tr -d '\r' | jq -r '.moduleData.toolData.additionalData')
          echo "DATA=$data" >> $GITHUB_ENV

      - name: Extract Namespace Value
        id: extract-namespace
        run: |
          # Extract namespace and store in environment variable
          namespace=$(echo "${{ toJson(github.event.inputs.payload) }}" | tr -d '\r' | jq -r '.projectKey')
          echo "NAMESPACE=$namespace" >> $GITHUB_ENV

      - name: Send email
        if: steps.check-operation.outputs['check-operation'] == 'Operation is Create'
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          subject: "test actions"
          to: snehilkumar4c@gmail.com
          from: ${{ secrets.GMAIL_USERNAME}}
          password: ${{ secrets.GMAIL_PASSWORD }}
          tls: true
          body: |
            Operation: Create
            
            Namespace: ${{ env.NAMESPACE }}
            
            Additional Details:
            ${{ env.DATA }}
          ignore_cert: true
