name: alert-notification

on: 
  workflow_dispatch:
    inputs:
      payload:
        description: 'JSON Payload'
        required: true

jobs: 
  run-script:
    runs-on: macOS-latest
    env:
      DATA: ''
      NAMESPACE: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if operation is Create
        id: check-operation
        run: |
          operation=$(echo "${{ toJson(github.event.inputs.payload) }}" | tr -d '\r' | jq -r '.operation')
          if [[ "$operation" == "Create" ]]; then
            echo "Operation is Create"
          else 
            echo "Operation is not Create. Skip"
            exit 0
          fi

      - name: Extract data
        run: | 
          export DATA=$(echo "${{ toJson(github.event.inputs.payload) }}" | tr -d '\r' | jq -r '.moduleData.toolData.additionalData')

      - name: Extract Namespace Value
        run: |
          export NAMESPACE=$(echo "${{ toJson(github.event.inputs.payload) }}" | tr -d '\r' | jq -r '.projectKey')

      - name: Send email
        if: steps.check-operation.outputs.check-operation == 'Operation is Create'
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: https://mail.google.com
          server_port: 587
          secure: false
          subject: "test actions"
          to: snehilkumar4c@gmail.com
          from: snehilkumar4c@gmail.com
          body: |
            Operation: Create
            
            Namespace: ${{ env.NAMESPACE }}
            
            Additional Details:
            ${{ env.DATA }}
            
          ignore_cert: true
