name: Process JSON Payload

on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'JSON Payload'
        required: true

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Operation
        id: extract-operation
        run: |
          json_data="${{ github.event.inputs.payload }}"
          operation=$(echo "$json_data" | jq -r '.operation')
          echo "Operation: $operation"
          echo "::set-output name=operation::$operation"

      - name: Extract Data
        id: extract-data
        run: |
          json_data="${{ github.event.inputs.payload }}"
          data=$(echo "$json_data" | jq -r '.moduleData.toolData.additionalData')
          echo "Additional Data: $data"
          echo "::set-output name=data::$data"

      - name: Extract Namespace
        id: extract-namespace
        run: |
          json_data="${{ github.event.inputs.payload }}"
          namespace=$(echo "$json_data" | jq -r '.projectKey')
          echo "Namespace: $namespace"
          echo "::set-output name=namespace::$namespace"

      - name: Send Email
        if: steps.extract-operation.outputs.operation == 'Create'
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          subject: "Process JSON Payload"
          to: your-email@example.com
          from: your-gmail-account@gmail.com
          password: ${{ secrets.GMAIL_PASSWORD }}
          tls: true
          body: |
            Operation: ${{ steps.extract-operation.outputs.operation }}
            
            Namespace: ${{ steps.extract-namespace.outputs.namespace }}
            
            Additional Details:
            ${{ steps.extract-data.outputs.data }}
          ignore_cert: true
