name: test-workflow
on: push
jobs: 
  test-workflow-job: 
    runs-on: macOS-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello-world.txt)" 
  
